FROM node:10-alpine AS cgm

MAINTAINER Nightscout Contributors

RUN apk add --no-cache --virtual build-dependencies \
build-base \
python3

RUN mkdir -p /opt/app
ADD . /opt/app
WORKDIR /opt/app
RUN chown -R node:node /opt/app
USER node

RUN npm install && \
  npm run postinstall && \
  npm run env && \
  npm audit fix

EXPOSE 1337

CMD ["node", "server.js"]
